version: '2'
services:
  app:
    build: ./docker/app
    ports:
      - "8080:80"
    volumes:
      - ./:/code
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=/code/app.py
    command: flask run --host=0.0.0.0 --port=80
  node:
    build: ./docker/node
    volumes_from:
      - app
    command: bash -c "npm i && npm run-script dev-watch"