version: '2'
services:
  app:
    build: ./docker/app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=/var/www/app.py
    command: >
      flask run --host=0.0.0.0 --port=80